language: python
python:
- 3.5
script:
- python setup.py test
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: QbCDwAb+YtES5H7nosbSS5PYHSti7XeD8UbTxn6uwLXelBvtts4cPgZJCa/FseD1+X+aNebVO0mCbNbdsswKtoMFdhOt+Dd8a4u1DTQwZwxl4zq/uu+FV62JmB4B4XGMWixeCfxjpTnWf/bvk/qv7FHZjKqbEWeQ7Lze5Tn6Yi95XSr31QncnBqacrqvKgIx0Ok5uVNz1U4gtjPm7+DSDy9h9oW5S8+wiPshW+fwk77ltA2WK868WHjsP4ZIEReIf5HPiN+SDo5KSBqnCbD0lqZWMSKZe3NIijJ9pWlO66MojfGmcZ3DkpjXwKSYDIdEX8uuFqWNbUAixB1qUSXVz+yjv7WlyvZ21TQ9pKhS+wOc+flMSevb5kLUgWlT0Le/1maoFLow7o8CwXko2wGLNUr8gNbtErX08Vz0Il2ADPQbAvfgsYo18CfYenb2Lky06tVP1pL21d2+YgG/ek8KrkBVY+cjJTcCCWrotmrQ/75XO6N+2cKkjguuWL4uN51/X9ZEZHds8p5b1CABMpTYopDlC1sj1QNv7FQyglJ422TWoPItOUvioF1+2agQ1KZSYqmLds04NLJcTDKe2kJdH+UKpG7FhmVcy6OJaw/C5msqSPv/zubYjRH6bpRQEDeP4IdqxxO69L93fXNXTvTx7orE/Wzdr+eJ9dMn3YjV2Ps=
  on:
    tags: true
    repo: cdumay/cdumay-error
