language: python
python:
- 3.5
install:
- pip --version
script:
- python setup.py build
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: PyMgXZS/TwfyaJdaazkAJ6mGQJVhRqvXD7fVKCyBODJsQ6S4ANZ3WxuxnxXzmCoVR38UWgp6r2/+W4HKXQMXk9X5cmuOrCb1Od9J+gP5cOcKjleXpU9Wq4jrR25saDJq5T9MvC63CN/Xam3qQpD9/X3TRf5uHVoe4JTo0VT3YZglx0MFsX7F9k16AtAtGlJWFPY6EyqM7CxZ7+na+WJVkkes6p/A9KWQXO75gpmxhPWiifS0tGe4cTmdctS2iLh2bQsvmK/OKc1xR4falemKavjij5Rs6zvCBOkXEiDrY1ehT+IlKchkAWZtOjI0uQdf2siHwqtB8ELZ53RhMAPvTkEii+V/Rlh4FgAg94/ZwyBQGWtHSZYFnSOHAtk/brAMFq7zTy4zDQI/65g/rETRSRwmAnOKhr2u5SWztnF1KQJA09utB/iUWzEgS49XFS/8ECTKcCidiD/L/RF6Q8zLBc/d/to98zENJo3zZHxinZEhcg4l25omlyLVbIrRq8JbYGu66dpxdmfVbVY1iSX4apCmGljK7pUgKX9SOZdyqLIbuHpf6hqFhaRDfvcMLH9MI1V2KR5YYBNNjrBxuK1K5i96aNQ3nfEAJKuq+PFvQZB5SSYglJtISOSMhzlDkiL1a41rg1lndDi5mnEKK2r51t9ezw3+BguA45nxOL3+QKY=
  on:
    tags: true
    repo: cdumay/cdumay-error
