language: python
python:
- 3.8
script:
- python setup.py build
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: P6Si8bzLXSOY3S+7XV1czRgb6ZtxLBFWT/j0UfWOg6fiZ66jsEEZPZSKcEZ4eGpSBgZq6OX0bDi/SBVF3TBahGNTl3ooDkoSUIIwNQXRH171MaWBAXLw2TdScov8NtlKZuhPyzMbuu3M3j+su7h81yNAMWNnNBgCeAWEiJrYa4i/WGXQGyyptkX9+aDz0r/3yEkgKMEP3hnCb+muewj3nWtwJrM/VFravDHJhRf56eOwS0MvgYqJqiD4bRF3VcLK9NScwqL0aTijsXzAv+DV9BgmXE/EFh8h3LgvzlnlsDP2vrOStHgnXvLe5YS2Ioi5Ym2PimhInXTkB+WpE6SaUxIZ/wslvRn4iO8wD+njlN2zK8ltLWrXP7xO0C4BnVWNIwdO/IyPR05hOgMATTO1BS0sqpJWhFBNRKARxSSyBbbDLfzBrJcosZH0snywj9nydzq4Dnc3AJNAhJ39Z0UiLXo7vP077uXqVXTh8bxTSdtGNQQIjnBFdZSClTsDrKCA5p8I3JEC3yYHxzhNxu8X1tPG9AOtsivpgCJlK+/xk7PtuvRipZR64cm0eVRVgFLZlWJxiuz9B6FFMbx8WNcOraDHCM3N6VSAV/G0SbOX+z37L+y9OsHz8vsz02//u0fntyoalbKXvQtlcR089BU70bT/S6xeTbkXc+Zpzg9YAaQ=
  on:
    tags: true
    repo: cdumay/cdumay-error
