language: python
python:
- 3.5
script:
- python setup.py test
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: KfGgbRgNIjtgUlh8ouywFF5yCkJ+LXzCCn2idXhkbBHtkdwGq0ibtibeMFHuefJzpFDQ1rMUFDL9i2OEbkCY7AqljwRwuiBJnoPC3zJBanDrPIBuobFnWdbkqwmowbXBltVkWMe0aQzZD/XEfr3D08Bjwc/dkrB9HzWulBbuZu0kVbEoDHd5r4mdHGLVR9hkma8lY9cDnRzypYgjoU5ABC0KTKRysVA6oIuokRmfJENxByq2ovoMJtRfI6POAVYc728CkYvam2yAwGvaw+dT7Q380IVcLbVw1AQ/gSmxsw3YcGeYrXN9SLH5VrSwn873aGdRVKNr6EukyiYvXQgpn/4uXYRQqsj/cam0ncFuFmkqCVeViXVjPTI4e7iMUD3FDKWZaHUZ3GBZgNojNDusIqtPy94Ci/gJiF2MJT02AakCFjqkhNApitjcnGChyojiMnzwX0qrVMaZzyvNZaXHiByMk95aDnmHlsiDKlU2vOZe376Xpc0+MCnbTogxPJ8MA43zjHfqCn0KklkLvjiZ88/h898fo9lOm8J0GeDLDVSnS2VC2+jzkZfhWveATyLJOZUJRsESp/O3tBF01fssXseLDtdKkeiQumlm9Nl83OZrl0cs3K9jFQKJvzMZSRXJ1z9n0/47wB8hMNGHaaZ7CqZH4Ry5iiVYUD0UYrryMb0=
  on:
    tags: true
    repo: cdumay/cdumay-error
